DDD: nsMLShom::Add Class Reference
nsMLShom::Add Class Reference
Public Member Functions
Add (const std::set< MLShom > &s, int ref=0)
bool operator== (const _MLShom &h) const
_MLShom * clone () const
size_t hash () const
unique table trivia
bool skip_variable (int) const
SHomNodeMap eval (const GSDD &d) const
virtual bool shouldCache () const
test if caching should be done : default means should cache
Private Attributes
std::set< MLShom > parameters
Constructor & Destructor Documentation
nsMLShom::Add::Add (const std::set< MLShom > & s, int ref = 0) inline
Referenced by clone().
Member Function Documentation
_MLShom* nsMLShom::Add::clone () const inline virtual
Implements _MLShom.
References Add().
SHomNodeMap nsMLShom::Add::eval (const GSDD & d) const inline virtual
Implements _MLShom.
References AdditiveMap< K, V, EqualKey >::addAll(), and parameters.
size_t nsMLShom::Add::hash () const inline virtual
unique table trivia
Implements _MLShom.
References parameters.
bool nsMLShom::Add::operator== (const _MLShom & h) const inline virtual
Implements _MLShom.
References parameters.
virtual bool _MLShom::shouldCache () const inline virtual inherited
test if caching should be done : default means should cache
Reimplemented in nsMLShom::Identity.
bool nsMLShom::Add::skip_variable (int) const inline
Member Data Documentation
std::set<MLShom> nsMLShom::Add::parameters private
Referenced by eval(), hash(), and operator==().
The documentation for this class was generated from the following file:
MLSHom.cpp
Please comment this page and report errors about it on the RefDocComments page.