DDD: SDED Class Reference
SDED Class Reference
#include <SDED.h>
Public Member Functions
GSDD eval ()
SDED (_SDED *c)
SDED ()
bool operator== (const SDED &) const
size_t hash () const
For storage in a hash table.
Static Public Member Functions
static GSDD add (const d3::set< GSDD >::type &)
static GSDD Shom (const GShom &, const GSDD &)
static unsigned int statistics ()
static void pstats (bool reinit=true)
static size_t peak ()
static void garbage ()
Private Attributes
_SDED * concret
Constructor & Destructor Documentation
SDED::SDED (_SDED * c) inline
SDED::SDED () inline
Member Function Documentation
GSDD SDED::add (const d3::set< GSDD >::type & s) static
References _SDED_Add::create(), eval(), and GSDD::null.
Referenced by sns::SApply2k::eval(), sns::SDomExtract::eval(), sns::LocalApply::eval(), StrongShom::eval(), sns::SLocalApply::eval(), sns::Add::eval(), sns::RecFireSat::eval(), and sns::MLShomAdapter::eval().
GSDD SDED::eval ()
References namespace_SDED::cache, concret, ext_hash_map< Key, Data, HashKey, EqualKey >::accessor::empty(), _SDED::eval(), ext_hash_map< Key, Data, HashKey, EqualKey >::find(), namespace_SDED::Hits, ext_hash_map< Key, Data, HashKey, EqualKey >::insert(), namespace_SDED::Misses, and GSDD::null.
Referenced by add(), operator*(), operator+(), operator-(), operator^(), and Shom().
void SDED::garbage () static
References namespace_SDED::cache, ext_hash_map< Key, Data, HashKey, EqualKey >::clear(), ext_hash_map< Key, Data, HashKey, EqualKey >::end(), namespace_SDED::Max_SDED, and ext_hash_map< Key, Data, HashKey, EqualKey >::size().
Referenced by MemoryManager::garbage().
size_t SDED::hash () const
For storage in a hash table.
References concret, and _SDED::hash().
bool SDED::operator== (const SDED & e) const
References concret.
size_t SDED::peak () static
References namespace_SDED::cache, namespace_SDED::Max_SDED, and ext_hash_map< Key, Data, HashKey, EqualKey >::size().
Referenced by Statistic::load().
void SDED::pstats (bool reinit = true) static
References namespace_SDED::Hits, namespace_SDED::Max_SDED, namespace_SDED::Misses, and statistics().
Referenced by MemoryManager::pstats().
GSDD SDED::Shom (const GShom & h, const GSDD & g) static
References _SDED_Shom::create(), and eval().
unsigned int SDED::statistics () static
References namespace_SDED::cache, and ext_hash_map< Key, Data, HashKey, EqualKey >::size().
Referenced by Statistic::load(), MemoryManager::nbSDED(), and pstats().
Member Data Documentation
_SDED* SDED::concret private
Referenced by eval(), hash(), and operator==().
The documentation for this class was generated from the following files:
SDED.h
SDED.cpp
Please comment this page and report errors about it on the RefDocComments page.