DDD: sns::SDomExtract Class Reference
sns::SDomExtract Class Reference
Extractor of variable domains for invert computations.
Public Member Functions
SDomExtract ()
SDomExtract (int t)
bool skip_variable (int) const
The skip_variable predicate indicates which variables are "don't care" with respect to this SHom.
bool is_selector () const
The isSelector predicate indicates a homomorphism that only selects paths in the SDD (no modifications, no additions) Tagging with isSelector() allows to enable optimizations and makes the homomorphism eligible as "condition" in ITE construct.
GSDD eval (const GSDD &d) const
The computation function responsible for evaluation over a node.
size_t hash () const
Hash key computation.
bool operator== (const _GShom &s) const
Comparator.
_GShom * clone () const
void print (std::ostream &os) const
GSDD has_image_skip (const GSDD &) const
virtual const GShom::range_t get_range () const
The range returns the dual of skip_variable, default implem considers that all variables are affected by this homomorphism.
virtual GSDD has_image (const GSDD &d) const
virtual GShom compose (const GShom &) const
virtual void mark () const
For garbage collection. Used in first phase of garbage collection.
void mark_if_refd () const
void ref () const
void deref () const
unsigned long int refCounter () const
bool is_marked () const
void set_mark (bool val) const
virtual GShom invert (const GSDD &) const
Static Public Member Functions
static const _GShom * get_concret (const GShom &gshom)
TODO : this is a dirty trick to allow us to do terms rewriting in Add, Fixpoint etc...
Public Attributes
int target
Detailed Description
Extractor of variable domains for invert computations.
Constructor & Destructor Documentation
sns::SDomExtract::SDomExtract () inline
Referenced by clone().
sns::SDomExtract::SDomExtract (int t) inline
Member Function Documentation
_GShom* sns::SDomExtract::clone () const inline virtual
Implements _GShom.
References SDomExtract().
GShom _GShom::compose (const GShom & r) const virtual inherited
References GShom::id, and GSDD::null.
Referenced by GShom::compose().
void _GShom::deref () const inline inherited
References _GShom::_refCounter.
Referenced by Shom::operator=(), and Shom::~Shom().
GSDD sns::SDomExtract::eval (const GSDD &) const inline virtual
The computation function responsible for evaluation over a node.
Users should not directly use this. Normal behavior is to use GShom::operator() that encapsulates this call with operation caching.
Implements _GShom.
References SDED::add(), GSDD::begin(), GSDD::end(), GSDD::null, GSDD::one, target, GSDD::top, and GSDD::variable().
static const _GShom* _GShom::get_concret (const GShom & gshom) inline static inherited
TODO : this is a dirty trick to allow us to do terms rewriting in Add, Fixpoint etc...
A more elegant architecture would be nice.
References GShom::concret.
Referenced by addCompositionParameter(), addParameter(), buildUnionParameters(), sns::RecFireSat::eval(), sns::Fixpoint::eval(), sns::Add::factorizeByLevel(), fixpoint(), GShom::GShom(), operator!(), operator&(), operator*(), sns::recFireSat(), sns::Inter::skip_variable(), sns::Add::skip_variable(), and sns::RightConcat::skip_variable().
virtual const GShom::range_t _GShom::get_range () const inline virtual inherited
The range returns the dual of skip_variable, default implem considers that all variables are affected by this homomorphism.
Reimplemented in sns::Fixpoint, sns::Compose, sns::RecFireSat, sns::Add, sns::And, sns::SNotCond, sns::SLocalApply, and sns::LocalApply.
References GShom::full_range.
Referenced by GShom::get_range().
GSDD _GShom::has_image (const GSDD & d) const virtual inherited
Reimplemented in sns::RightConcat, sns::LeftConcat, sns::Compose, sns::Add, sns::And, sns::SNotCond, sns::SLocalApply, StrongShom, sns::LocalApply, sns::Inter, and sns::Identity.
References _GShom::GShom.
Referenced by sns::Inter::has_image(), sns::SNotCond::has_image(), sns::Compose::has_image(), and _GShom::has_image_skip().
GSDD _GShom::has_image_skip (const GSDD & d) const inherited
References GSDD::begin(), GSDD::end(), GShom::has_image(), _GShom::has_image(), GShom::id, GSDD::null, GSDD::one, _GShom::skip_variable(), GSDD::top, and GSDD::variable().
size_t sns::SDomExtract::hash () const inline virtual
Hash key computation.
It is essential for good hash table operation that the spread of the keys be as good as possible. Also, fast hash key computation is a good design goal. Note that bad hash functions will yield more collisions, thus equality comparisons which may be quite costly.
Implements _GShom.
References target.
virtual GShom _GShom::invert (const GSDD &) const inline virtual inherited
Reimplemented in sns::Fixpoint, sns::HomMinus, sns::Minus, sns::Compose, sns::RecFireSat, sns::Add, sns::And, sns::SLocalApply, sns::LocalApply, sns::Inter, sns::Mult, sns::SApply2k, sns::Constant, and sns::Identity.
References _GShom::is_selector(), Shom::null, and _GShom::print().
Referenced by GShom::invert().
bool _GShom::is_marked () const inline inherited
References _GShom::_refCounter.
Referenced by _GShom::set_mark().
bool sns::SDomExtract::is_selector () const inline virtual
The isSelector predicate indicates a homomorphism that only selects paths in the SDD (no modifications, no additions) Tagging with isSelector() allows to enable optimizations and makes the homomorphism eligible as "condition" in ITE construct.
Reimplemented from _GShom.
virtual void _GShom::mark () const inline virtual inherited
For garbage collection. Used in first phase of garbage collection.
Reimplemented in sns::MLShomAdapter, sns::Fixpoint, sns::HomMinus, sns::Minus, sns::RightConcat, sns::LeftConcat, sns::Compose, sns::RecFireSat, sns::Add, sns::And, sns::SNotCond, sns::SLocalApply, sns::LocalApply, sns::Inter, sns::Mult, sns::SApply2k, and sns::Constant.
Referenced by _GShom::set_mark().
void _GShom::mark_if_refd () const inline inherited
References _GShom::refCounter(), and _GShom::set_mark().
bool sns::SDomExtract::operator== (const _GShom & h) const inline virtual
Comparator.
Used in case of hash collision. Should be appropriately defined in derived classes, in particular in user defined homomorphisms.
Implements _GShom.
References target.
void sns::SDomExtract::print (std::ostream & os) const inline virtual
Implements _GShom.
References target.
void _GShom::ref () const inline inherited
References _GShom::_refCounter.
Referenced by Shom::operator=(), and Shom::Shom().
unsigned long int _GShom::refCounter () const inline inherited
References _GShom::_refCounter.
Referenced by _GShom::mark_if_refd(), Shom::operator=(), GShom::refCounter(), and Shom::~Shom().
void _GShom::set_mark (bool val) const inline inherited
References _GShom::_refCounter, _GShom::is_marked(), and _GShom::mark().
Referenced by GShom::garbage(), GShom::mark(), and _GShom::mark_if_refd().
bool sns::SDomExtract::skip_variable (int) const inline virtual
The skip_variable predicate indicates which variables are "don't care" with respect to this SHom.
This is defined as a StrongHom with : phi(var,val) { if (skip_variable(var)) return GShom(var, val, this); else { real behavior } }
Reimplemented from _GShom.
Member Data Documentation
int sns::SDomExtract::target
Referenced by eval(), hash(), operator==(), and print().
The documentation for this class was generated from the following file:
SHom.cpp
Please comment this page and report errors about it on the RefDocComments page.