DDD: DED Class Reference
DED Class Reference
#include <DED.h>
Public Member Functions
GDDD eval ()
DED (_DED *c)
DED ()
bool operator== (const DED &) const
size_t hash () const
For storage in a hash table.
Static Public Member Functions
static GDDD add (const d3::set< GDDD >::type &)
static GDDD hom (const GHom &, const GDDD &)
static unsigned int statistics ()
static void pstats (bool reinit=true)
static size_t peak ()
static void garbage ()
Private Attributes
_DED * concret
Friends
struct std::equal_to< DED >
Constructor & Destructor Documentation
DED::DED (_DED * c) inline
DED::DED () inline
Member Function Documentation
GDDD DED::add (const d3::set< GDDD >::type &) static
References GDDD::begin(), _DED_Add::create(), eval(), and GDDD::null.
Referenced by _DED_Add::eval(), Apply2k::eval(), DomExtract::eval(), StrongHom::eval(), Add::eval(), Fixpoint::eval(), MLHomAdapter::eval(), and operator+().
GDDD DED::eval ()
References concret, ext_hash_map< Key, Data, HashKey, EqualKey >::accessor::empty(), _DED::eval(), Hits, Cache< FuncType, ParamType, ResType, EvalFunc >::insert(), Misses, and GDDD::null.
Referenced by add(), hom(), operator*(), operator-(), and operator^().
void DED::garbage () static
References Cache< FuncType, ParamType, ResType, EvalFunc >::clear(), DEDpeak, and Cache< FuncType, ParamType, ResType, EvalFunc >::size().
Referenced by MemoryManager::garbage().
size_t DED::hash () const
For storage in a hash table.
References concret, and _DED::hash().
GDDD DED::hom (const GHom & h, const GDDD & g) static
References _DED_Hom::create(), and eval().
bool DED::operator== (const DED & e) const
References concret.
size_t DED::peak () static
References DEDpeak, and Cache< FuncType, ParamType, ResType, EvalFunc >::size().
Referenced by Statistic::load().
void DED::pstats (bool reinit = true) static
References Hits, Misses, and Cache< FuncType, ParamType, ResType, EvalFunc >::size().
Referenced by MemoryManager::pstats().
unsigned int DED::statistics () static
References Cache< FuncType, ParamType, ResType, EvalFunc >::size().
Referenced by Statistic::load(), and MemoryManager::nbDED().
Friends And Related Function Documentation
friend struct std::equal_to< DED > friend
Member Data Documentation
_DED* DED::concret private
Referenced by eval(), hash(), and operator==().
The documentation for this class was generated from the following files:
DED.h
DED.cpp
Please comment this page and report errors about it on the RefDocComments page.