DDD: nsMLHom::LeftConcat Class Reference
nsMLHom::LeftConcat Class Reference
Public Member Functions
LeftConcat (const GDDD &l, const MLHom &_h, int ref=0)
bool operator== (const _MLHom &other) const
_MLHom * clone () const
size_t hash () const
unique table trivia
bool skip_variable (int) const
HomNodeMap eval (const GDDD &d) const
virtual bool shouldCache () const
test if caching should be done : default means should cache
Private Attributes
GDDD left
MLHom h
Constructor & Destructor Documentation
nsMLHom::LeftConcat::LeftConcat (const GDDD & l, const MLHom & _h, int ref = 0) inline
Referenced by clone().
Member Function Documentation
_MLHom* nsMLHom::LeftConcat::clone () const inline virtual
Implements _MLHom.
References LeftConcat().
HomNodeMap nsMLHom::LeftConcat::eval (const GDDD & d) const inline virtual
Implements _MLHom.
References AdditiveMap< K, V, EqualKey >::add(), AdditiveMap< K, V, EqualKey >::begin(), AdditiveMap< K, V, EqualKey >::end(), h, and left.
size_t nsMLHom::LeftConcat::hash () const inline virtual
unique table trivia
Implements _MLHom.
References h, MLHom::hash(), GDDD::hash(), and left.
bool nsMLHom::LeftConcat::operator== (const _MLHom & other) const inline virtual
Implements _MLHom.
References h, and left.
virtual bool _MLHom::shouldCache () const inline virtual inherited
test if caching should be done : default means should cache
Reimplemented in nsMLHom::Identity.
bool nsMLHom::LeftConcat::skip_variable (int) const inline
Member Data Documentation
MLHom nsMLHom::LeftConcat::h private
Referenced by eval(), hash(), and operator==().
GDDD nsMLHom::LeftConcat::left private
Referenced by eval(), hash(), and operator==().
The documentation for this class was generated from the following file:
MLHom.cpp
Please comment this page and report errors about it on the RefDocComments page.