DDD: _GShom Class Reference
_GShom Class Reference abstract
The concrete data class for Homomorphisms.
#include <SHom.h>
Public Member Functions
GSDD has_image_skip (const GSDD &) const
virtual bool skip_variable (int) const
The skip_variable predicate indicates which variables are "don't care" with respect to this SHom.
virtual bool is_selector () const
The isSelector predicate indicates a homomorphism that only selects paths in the SDD (no modifications, no additions) Tagging with isSelector() allows to enable optimizations and makes the homomorphism eligible as "condition" in ITE construct.
virtual const GShom::range_t get_range () const
The range returns the dual of skip_variable, default implem considers that all variables are affected by this homomorphism.
_GShom (int ref=0)
Constructor.
virtual ~_GShom ()
Destructor.
virtual bool operator== (const _GShom &h) const =0
Comparator.
virtual size_t hash () const =0
Hash key computation.
virtual _GShom * clone () const =0
virtual GSDD has_image (const GSDD &d) const
virtual GShom compose (const GShom &) const
virtual GSDD eval (const GSDD &) const =0
The computation function responsible for evaluation over a node.
virtual void mark () const
For garbage collection. Used in first phase of garbage collection.
void mark_if_refd () const
void ref () const
void deref () const
unsigned long int refCounter () const
bool is_marked () const
void set_mark (bool val) const
virtual void print (std::ostream &os) const =0
virtual GShom invert (const GSDD &) const
Static Public Member Functions
static const _GShom * get_concret (const GShom &gshom)
TODO : this is a dirty trick to allow us to do terms rewriting in Add, Fixpoint etc...
Private Member Functions
GSDD eval_skip (const GSDD &) const
The procedure responsible for propagating efficiently across "skipped" variable nodes.
virtual bool immediat () const
For operation cache management.
Private Attributes
int _refCounter
For garbage collection.
Friends
class GShom
open access to container class GShom.
class Shom
open access to container class Shom.
Detailed Description
The concrete data class for Homomorphisms.
Users should not use this (private) class directly, but may use it indirectly by deriving user homomorphisms from the StrongShom class.
Constructor & Destructor Documentation
_GShom::_GShom (int ref = 0) inline
Constructor.
Note this class is abstract, so this is only used in initialization list of derived classes constructors (hard coded operations and StrongShom).
virtual _GShom::~_GShom () inline virtual
Destructor.
Default behavior.
Todo:
Remove this declaration ? compiler generated version sufficient.
Member Function Documentation
virtual _GShom* _GShom::clone () const pure virtual
Implemented in sns::MLShomAdapter, sns::Fixpoint, sns::HomMinus, sns::Minus, sns::RightConcat, sns::LeftConcat, sns::Compose, sns::RecFireSat, sns::Add, sns::And, sns::SNotCond, sns::SLocalApply, sns::LocalApply, sns::SDomExtract, sns::Inter, sns::Mult, sns::SApply2k, sns::Constant, and sns::Identity.
GShom _GShom::compose (const GShom & r) const virtual
References GShom::id, and GSDD::null.
Referenced by GShom::compose().
void _GShom::deref () const inline
References _refCounter.
Referenced by Shom::operator=(), and Shom::~Shom().
virtual GSDD _GShom::eval (const GSDD &) const pure virtual
The computation function responsible for evaluation over a node.
Users should not directly use this. Normal behavior is to use GShom::operator() that encapsulates this call with operation caching.
Implemented in sns::MLShomAdapter, sns::Fixpoint, sns::HomMinus, sns::Minus, sns::RightConcat, sns::LeftConcat, sns::Compose, sns::RecFireSat, sns::Add, sns::And, sns::SNotCond, sns::SLocalApply, StrongShom, sns::LocalApply, sns::SDomExtract, sns::Inter, sns::Mult, sns::SApply2k, sns::Constant, and sns::Identity.
Referenced by eval_skip().
GSDD _GShom::eval_skip (const GSDD & d) const private
The procedure responsible for propagating efficiently across "skipped" variable nodes.
References GSDD::begin(), GSDD::end(), eval(), GShom::id, immediat(), GSDD::nbsons(), GSDD::null, GSDD::one, skip_variable(), square_union(), GSDD::top, and GSDD::variable().
Referenced by GShom::eval().
static const _GShom* _GShom::get_concret (const GShom & gshom) inline static
TODO : this is a dirty trick to allow us to do terms rewriting in Add, Fixpoint etc...
A more elegant architecture would be nice.
References GShom::concret.
Referenced by addCompositionParameter(), addParameter(), buildUnionParameters(), sns::RecFireSat::eval(), sns::Fixpoint::eval(), sns::Add::factorizeByLevel(), fixpoint(), GShom::GShom(), operator!(), operator&(), operator*(), sns::recFireSat(), sns::Inter::skip_variable(), sns::Add::skip_variable(), and sns::RightConcat::skip_variable().
virtual const GShom::range_t _GShom::get_range () const inline virtual
The range returns the dual of skip_variable, default implem considers that all variables are affected by this homomorphism.
Reimplemented in sns::Fixpoint, sns::Compose, sns::RecFireSat, sns::Add, sns::And, sns::SNotCond, sns::SLocalApply, and sns::LocalApply.
References GShom::full_range.
Referenced by GShom::get_range().
GSDD _GShom::has_image (const GSDD & d) const virtual
Reimplemented in sns::RightConcat, sns::LeftConcat, sns::Compose, sns::Add, sns::And, sns::SNotCond, sns::SLocalApply, StrongShom, sns::LocalApply, sns::Inter, and sns::Identity.
References GShom.
Referenced by sns::Inter::has_image(), sns::SNotCond::has_image(), sns::Compose::has_image(), and has_image_skip().
GSDD _GShom::has_image_skip (const GSDD & d) const
References GSDD::begin(), GSDD::end(), GShom::has_image(), has_image(), GShom::id, GSDD::null, GSDD::one, skip_variable(), GSDD::top, and GSDD::variable().
virtual size_t _GShom::hash () const pure virtual
Hash key computation.
It is essential for good hash table operation that the spread of the keys be as good as possible. Also, fast hash key computation is a good design goal. Note that bad hash functions will yield more collisions, thus equality comparisons which may be quite costly.
Implemented in sns::MLShomAdapter, sns::Fixpoint, sns::HomMinus, sns::Minus, sns::RightConcat, sns::LeftConcat, sns::Compose, sns::RecFireSat, sns::Add, sns::And, sns::SNotCond, sns::SLocalApply, sns::LocalApply, sns::SDomExtract, sns::Inter, sns::Mult, sns::SApply2k, sns::Constant, and sns::Identity.
virtual bool _GShom::immediat () const inline private virtual
For operation cache management.
If immediat==true, eval is called without attempting a cache hit. Currently only the constant homomorphism has this attribute set to true. Overload and return true for immediate computations.
Reimplemented in sns::Constant, and sns::Identity.
Referenced by eval_skip(), and GShom::operator()().
virtual GShom _GShom::invert (const GSDD &) const inline virtual
Reimplemented in sns::Fixpoint, sns::HomMinus, sns::Minus, sns::Compose, sns::RecFireSat, sns::Add, sns::And, sns::SLocalApply, sns::LocalApply, sns::Inter, sns::Mult, sns::SApply2k, sns::Constant, and sns::Identity.
References is_selector(), Shom::null, and print().
Referenced by GShom::invert().
bool _GShom::is_marked () const inline
References _refCounter.
Referenced by set_mark().
virtual bool _GShom::is_selector () const inline virtual
The isSelector predicate indicates a homomorphism that only selects paths in the SDD (no modifications, no additions) Tagging with isSelector() allows to enable optimizations and makes the homomorphism eligible as "condition" in ITE construct.
Reimplemented in sns::Fixpoint, sns::HomMinus, sns::Minus, sns::Compose, sns::RecFireSat, sns::Add, sns::And, sns::SNotCond, sns::SLocalApply, sns::LocalApply, sns::SDomExtract, sns::Inter, sns::Mult, sns::SApply2k, sns::Constant, and sns::Identity.
Referenced by invert(), and GShom::is_selector().
virtual void _GShom::mark () const inline virtual
For garbage collection. Used in first phase of garbage collection.
Reimplemented in sns::MLShomAdapter, sns::Fixpoint, sns::HomMinus, sns::Minus, sns::RightConcat, sns::LeftConcat, sns::Compose, sns::RecFireSat, sns::Add, sns::And, sns::SNotCond, sns::SLocalApply, sns::LocalApply, sns::Inter, sns::Mult, sns::SApply2k, and sns::Constant.
Referenced by set_mark().
void _GShom::mark_if_refd () const inline
References refCounter(), and set_mark().
virtual bool _GShom::operator== (const _GShom & h) const pure virtual
Comparator.
Used in case of hash collision. Should be appropriately defined in derived classes, in particular in user defined homomorphisms.
Implemented in sns::MLShomAdapter, sns::Fixpoint, sns::HomMinus, sns::Minus, sns::RightConcat, sns::LeftConcat, sns::Compose, sns::RecFireSat, sns::Add, sns::And, sns::SNotCond, sns::SLocalApply, sns::LocalApply, StrongShom, sns::SDomExtract, sns::Inter, sns::Mult, sns::SApply2k, sns::Constant, and sns::Identity.
virtual void _GShom::print (std::ostream & os) const pure virtual
Implemented in sns::MLShomAdapter, sns::Fixpoint, sns::HomMinus, sns::Minus, sns::RightConcat, sns::LeftConcat, sns::Compose, sns::RecFireSat, sns::Add, sns::And, sns::SNotCond, sns::SLocalApply, sns::LocalApply, StrongShom, sns::SDomExtract, sns::Inter, sns::Mult, sns::SApply2k, sns::Constant, and sns::Identity.
Referenced by invert(), and operator<<().
void _GShom::ref () const inline
References _refCounter.
Referenced by Shom::operator=(), and Shom::Shom().
unsigned long int _GShom::refCounter () const inline
References _refCounter.
Referenced by mark_if_refd(), Shom::operator=(), GShom::refCounter(), and Shom::~Shom().
void _GShom::set_mark (bool val) const inline
References _refCounter, is_marked(), and mark().
Referenced by GShom::garbage(), GShom::mark(), and mark_if_refd().
virtual bool _GShom::skip_variable (int) const inline virtual
The skip_variable predicate indicates which variables are "don't care" with respect to this SHom.
This is defined as a StrongHom with : phi(var,val) { if (skip_variable(var)) return GShom(var, val, this); else { real behavior } }
Reimplemented in sns::Fixpoint, sns::RightConcat, sns::Compose, sns::RecFireSat, sns::Add, sns::And, sns::SNotCond, sns::SLocalApply, sns::LocalApply, sns::SDomExtract, sns::Inter, sns::SApply2k, and sns::Identity.
Referenced by eval_skip(), has_image_skip(), GShom::skip_variable(), sns::Inter::skip_variable(), sns::Add::skip_variable(), and sns::RightConcat::skip_variable().
Friends And Related Function Documentation
friend class GShom friend
open access to container class GShom.
Referenced by sns::Add::eval(), sns::RecFireSat::eval(), sns::Fixpoint::eval(), has_image(), and sns::Compose::invert().
friend class Shom friend
open access to container class Shom.
Referenced by sns::Fixpoint::eval().
Member Data Documentation
int _GShom::_refCounter mutable private
For garbage collection.
Counts the number of times a _GShom is referenced from the context of an Shom. For garbage collection: lowest bit of refCounter gives marking value for mark&sweep. Used in the two phase garbage collection process. A Shom that is not marked after the first pass over the unicity table, will be sweeped in the second phase. Outside of garbage collection routine, marking should always bear the value false.
Referenced by deref(), is_marked(), ref(), refCounter(), and set_mark().
The documentation for this class was generated from the following files:
SHom.h
SHom.cpp
Please comment this page and report errors about it on the RefDocComments page.