DDD: StrongMLHom Class Reference
StrongMLHom Class Reference abstract
#include <MLHom.h>
Public Member Functions
bool operator== (const _MLHom &h) const
virtual bool operator== (const StrongMLHom &) const =0
HomNodeMap eval (const GDDD &) const
virtual HomHomMap phi (int var, int val) const =0
User defined behavior is input through this function.
virtual HomNodeMap phiOne () const =0
virtual bool shouldCache () const
test if caching should be done : default means should cache
virtual size_t hash () const =0
unique table trivia
virtual _MLHom * clone () const =0
Member Function Documentation
virtual _MLHom* _MLHom::clone () const pure virtual inherited
Implemented in nsMLHom::LeftConcat, nsMLHom::ConstantUp, nsMLHom::GHomAdapter, nsMLHom::Add, and nsMLHom::Identity.
HomNodeMap StrongMLHom::eval (const GDDD & d) const virtual
Implements _MLHom.
References AdditiveMap< K, V, EqualKey >::add(), AdditiveMap< K, V, EqualKey >::begin(), GDDD::begin(), AdditiveMap< K, V, EqualKey >::end(), GDDD::end(), GHom::id, GDDD::null, GDDD::one, phi(), phiOne(), GDDD::top, and GDDD::variable().
virtual size_t _MLHom::hash () const pure virtual inherited
unique table trivia
Implemented in nsMLHom::LeftConcat, nsMLHom::ConstantUp, nsMLHom::GHomAdapter, nsMLHom::Add, and nsMLHom::Identity.
bool StrongMLHom::operator== (const _MLHom & h) const virtual
Implements _MLHom.
virtual bool StrongMLHom::operator== (const StrongMLHom &) const pure virtual
virtual HomHomMap StrongMLHom::phi (int var, int val) const pure virtual
User defined behavior is input through this function.
Referenced by eval().
virtual HomNodeMap StrongMLHom::phiOne () const pure virtual
Referenced by eval().
virtual bool _MLHom::shouldCache () const inline virtual inherited
test if caching should be done : default means should cache
Reimplemented in nsMLHom::Identity.
The documentation for this class was generated from the following files:
MLHom.h
MLHom.cpp
Please comment this page and report errors about it on the RefDocComments page.