DDD: sns::Identity Class Reference
sns::Identity Class Reference
Public Member Functions
Identity (int ref=0)
bool immediat () const
For operation cache management.
bool operator== (const _GShom &) const
Comparator.
size_t hash () const
Hash key computation.
_GShom * clone () const
bool is_selector () const
The isSelector predicate indicates a homomorphism that only selects paths in the SDD (no modifications, no additions) Tagging with isSelector() allows to enable optimizations and makes the homomorphism eligible as "condition" in ITE construct.
bool skip_variable (int) const
The skip_variable predicate indicates which variables are "don't care" with respect to this SHom.
GSDD eval (const GSDD &d) const
The computation function responsible for evaluation over a node.
GShom invert (const GSDD &pot) const
GSDD has_image (const GSDD &d) const
void print (std::ostream &os) const
GSDD has_image_skip (const GSDD &) const
virtual const GShom::range_t get_range () const
The range returns the dual of skip_variable, default implem considers that all variables are affected by this homomorphism.
virtual GShom compose (const GShom &) const
virtual void mark () const
For garbage collection. Used in first phase of garbage collection.
void mark_if_refd () const
void ref () const
void deref () const
unsigned long int refCounter () const
bool is_marked () const
void set_mark (bool val) const
Static Public Member Functions
static const _GShom * get_concret (const GShom &gshom)
TODO : this is a dirty trick to allow us to do terms rewriting in Add, Fixpoint etc...
Constructor & Destructor Documentation
sns::Identity::Identity (int ref = 0) inline
Referenced by clone().
Member Function Documentation
_GShom* sns::Identity::clone () const inline virtual
Implements _GShom.
References Identity().
GShom _GShom::compose (const GShom & r) const virtual inherited
References GShom::id, and GSDD::null.
Referenced by GShom::compose().
void _GShom::deref () const inline inherited
References _GShom::_refCounter.
Referenced by Shom::operator=(), and Shom::~Shom().
GSDD sns::Identity::eval (const GSDD &) const inline virtual
The computation function responsible for evaluation over a node.
Users should not directly use this. Normal behavior is to use GShom::operator() that encapsulates this call with operation caching.
Implements _GShom.
static const _GShom* _GShom::get_concret (const GShom & gshom) inline static inherited
TODO : this is a dirty trick to allow us to do terms rewriting in Add, Fixpoint etc...
A more elegant architecture would be nice.
References GShom::concret.
Referenced by addCompositionParameter(), addParameter(), buildUnionParameters(), sns::RecFireSat::eval(), sns::Fixpoint::eval(), sns::Add::factorizeByLevel(), fixpoint(), GShom::GShom(), operator!(), operator&(), operator*(), sns::recFireSat(), sns::Inter::skip_variable(), sns::Add::skip_variable(), and sns::RightConcat::skip_variable().
virtual const GShom::range_t _GShom::get_range () const inline virtual inherited
The range returns the dual of skip_variable, default implem considers that all variables are affected by this homomorphism.
Reimplemented in sns::Fixpoint, sns::Compose, sns::RecFireSat, sns::Add, sns::And, sns::SNotCond, sns::SLocalApply, and sns::LocalApply.
References GShom::full_range.
Referenced by GShom::get_range().
GSDD sns::Identity::has_image (const GSDD & d) const inline virtual
Reimplemented from _GShom.
GSDD _GShom::has_image_skip (const GSDD & d) const inherited
References GSDD::begin(), GSDD::end(), GShom::has_image(), _GShom::has_image(), GShom::id, GSDD::null, GSDD::one, _GShom::skip_variable(), GSDD::top, and GSDD::variable().
size_t sns::Identity::hash () const inline virtual
Hash key computation.
It is essential for good hash table operation that the spread of the keys be as good as possible. Also, fast hash key computation is a good design goal. Note that bad hash functions will yield more collisions, thus equality comparisons which may be quite costly.
Implements _GShom.
bool sns::Identity::immediat () const inline virtual
For operation cache management.
If immediat==true, eval is called without attempting a cache hit. Currently only the constant homomorphism has this attribute set to true. Overload and return true for immediate computations.
Reimplemented from _GShom.
GShom sns::Identity::invert (const GSDD & pot) const inline virtual
Reimplemented from _GShom.
bool _GShom::is_marked () const inline inherited
References _GShom::_refCounter.
Referenced by _GShom::set_mark().
bool sns::Identity::is_selector () const inline virtual
The isSelector predicate indicates a homomorphism that only selects paths in the SDD (no modifications, no additions) Tagging with isSelector() allows to enable optimizations and makes the homomorphism eligible as "condition" in ITE construct.
Reimplemented from _GShom.
virtual void _GShom::mark () const inline virtual inherited
For garbage collection. Used in first phase of garbage collection.
Reimplemented in sns::MLShomAdapter, sns::Fixpoint, sns::HomMinus, sns::Minus, sns::RightConcat, sns::LeftConcat, sns::Compose, sns::RecFireSat, sns::Add, sns::And, sns::SNotCond, sns::SLocalApply, sns::LocalApply, sns::Inter, sns::Mult, sns::SApply2k, and sns::Constant.
Referenced by _GShom::set_mark().
void _GShom::mark_if_refd () const inline inherited
References _GShom::refCounter(), and _GShom::set_mark().
bool sns::Identity::operator== (const _GShom & h) const inline virtual
Comparator.
Used in case of hash collision. Should be appropriately defined in derived classes, in particular in user defined homomorphisms.
Implements _GShom.
void sns::Identity::print (std::ostream & os) const inline virtual
Implements _GShom.
void _GShom::ref () const inline inherited
References _GShom::_refCounter.
Referenced by Shom::operator=(), and Shom::Shom().
unsigned long int _GShom::refCounter () const inline inherited
References _GShom::_refCounter.
Referenced by _GShom::mark_if_refd(), Shom::operator=(), GShom::refCounter(), and Shom::~Shom().
void _GShom::set_mark (bool val) const inline inherited
References _GShom::_refCounter, _GShom::is_marked(), and _GShom::mark().
Referenced by GShom::garbage(), GShom::mark(), and _GShom::mark_if_refd().
bool sns::Identity::skip_variable (int) const inline virtual
The skip_variable predicate indicates which variables are "don't care" with respect to this SHom.
This is defined as a StrongHom with : phi(var,val) { if (skip_variable(var)) return GShom(var, val, this); else { real behavior } }
Reimplemented from _GShom.
The documentation for this class was generated from the following file:
SHom.cpp
Please comment this page and report errors about it on the RefDocComments page.