DDD: nsMLShom::Identity Class Reference
nsMLShom::Identity Class Reference
Public Member Functions
Identity (int ref=0)
virtual bool shouldCache () const
test if caching should be done : default means should cache
bool operator== (const _MLShom &) const
size_t hash () const
unique table trivia
_MLShom * clone () const
bool skip_variable (int) const
SHomNodeMap eval (const GSDD &d) const
Constructor & Destructor Documentation
nsMLShom::Identity::Identity (int ref = 0) inline
Referenced by clone().
Member Function Documentation
_MLShom* nsMLShom::Identity::clone () const inline virtual
Implements _MLShom.
References Identity().
SHomNodeMap nsMLShom::Identity::eval (const GSDD & d) const inline virtual
Implements _MLShom.
References AdditiveMap< K, V, EqualKey >::add(), and GShom::id.
size_t nsMLShom::Identity::hash () const inline virtual
unique table trivia
Implements _MLShom.
bool nsMLShom::Identity::operator== (const _MLShom &) const inline virtual
Implements _MLShom.
virtual bool nsMLShom::Identity::shouldCache () const inline virtual
test if caching should be done : default means should cache
Reimplemented from _MLShom.
bool nsMLShom::Identity::skip_variable (int) const inline
The documentation for this class was generated from the following file:
MLSHom.cpp
Please comment this page and report errors about it on the RefDocComments page.