DDD: nsMLShom::ConstantUp Class Reference
nsMLShom::ConstantUp Class Reference
Public Member Functions
ConstantUp (const GShom &uup, const MLShom &ddown)
bool operator== (const _MLShom &other) const
_MLShom * clone () const
size_t hash () const
unique table trivia
bool skip_variable (int) const
SHomNodeMap eval (const GSDD &d) const
virtual bool shouldCache () const
test if caching should be done : default means should cache
Private Attributes
GShom up
MLShom down
Constructor & Destructor Documentation
nsMLShom::ConstantUp::ConstantUp (const GShom & uup, const MLShom & ddown) inline
Referenced by clone().
Member Function Documentation
_MLShom* nsMLShom::ConstantUp::clone () const inline virtual
Implements _MLShom.
References ConstantUp().
SHomNodeMap nsMLShom::ConstantUp::eval (const GSDD & d) const inline virtual
Implements _MLShom.
References AdditiveMap< K, V, EqualKey >::add(), AdditiveMap< K, V, EqualKey >::begin(), down, AdditiveMap< K, V, EqualKey >::end(), and up.
size_t nsMLShom::ConstantUp::hash () const inline virtual
unique table trivia
Implements _MLShom.
References down, MLShom::hash(), GShom::hash(), and up.
bool nsMLShom::ConstantUp::operator== (const _MLShom & other) const inline virtual
Implements _MLShom.
References down, and up.
virtual bool _MLShom::shouldCache () const inline virtual inherited
test if caching should be done : default means should cache
Reimplemented in nsMLShom::Identity.
bool nsMLShom::ConstantUp::skip_variable (int) const inline
Member Data Documentation
MLShom nsMLShom::ConstantUp::down private
Referenced by eval(), hash(), and operator==().
GShom nsMLShom::ConstantUp::up private
Referenced by eval(), hash(), and operator==().
The documentation for this class was generated from the following file:
MLSHom.cpp
Please comment this page and report errors about it on the RefDocComments page.