DDD: _setVarConst Class Reference
_setVarConst Class Reference
Public Member Functions
_setVarConst (int vr, int vl)
bool skip_variable (int vr) const
The skip_variable predicate indicates which variables are "don't care" with respect to this SHom.
const GHom::range_t get_range () const
The range returns the dual of skip_variable, default implem considers that all variables are affected by this homomorphism.
GDDD phiOne () const
Evaluation over terminal GDDD::one.
GHom phi (int vr, int vl) const
Evaluation over an arbitrary arc of a SDD.
GHom invert (const GDDD &potall) const
returns the predescessor homomorphism, using pot to determine variable domains
size_t hash () const
Hash key computation.
void print (std::ostream &os) const
pretty print
bool operator== (const StrongHom &s) const
Comparator is pure virtual. Define a behavior in user homomorphisms.
_GHom * clone () const
bool operator== (const _GHom &h) const
Comparator for unicity table.
GDDD eval (const GDDD &) const
The evaluation mechanism of strong homomorphisms.
virtual GDDD has_image (const GDDD &) const
GDDD has_image_skip (const GDDD &) const
virtual bool is_selector () const
The isSelector predicate indicates a homomorphism that only selects paths in the SDD (no modifications, no additions) Tagging with isSelector() allows to enable optimizations and makes the homomorphism eligible as "condition" in ITE construct.
bool operator< (const _GHom &h) const
Ordering between _GHom. It is the chronological ordering of creation.
virtual void mark () const
For garbage collection. Used in first phase of garbage collection.
virtual GHom negate () const
returns a negation of a selector homomorphism h, such that h.negate() (d) = d - h(d)
virtual GHom compose (const GHom &r) const
Static Public Member Functions
static const _GHom * get_concret (const GHom &ghom)
Private Attributes
int var
int val
Constructor & Destructor Documentation
_setVarConst::_setVarConst (int vr, int vl) inline
Referenced by clone().
Member Function Documentation
_GHom* _setVarConst::clone () const inline virtual
Implements _GHom.
References _setVarConst().
GHom _GHom::compose (const GHom & r) const virtual inherited
Reimplemented in _VarCompVar, and _VarCompState.
References GHom::id, and GDDD::null.
Referenced by _VarCompState::compose(), GHom::compose(), and _VarCompVar::compose().
GDDD StrongHom::eval (const GDDD & d) const virtual inherited
The evaluation mechanism of strong homomorphisms.
Evaluation is defined as :
Let an SDD d= (var, Union_i (val_i, d_i))
h (d) = Sum_i (phi(var, val_i) (d_i))
Implements _GHom.
References DED::add(), GDDD::begin(), GDDD::end(), GDDD::null, GDDD::one, StrongHom::phi(), StrongHom::phiOne(), GDDD::top, and GDDD::variable().
static const _GHom* _GHom::get_concret (const GHom & ghom) inline static inherited
References GHom::concret.
Referenced by Add::Add(), addCompositionParameter(), _VarCompState::compose(), _VarCompVar::compose(), And::eval(), Fixpoint::eval(), fixpoint(), Fixpoint::has_image(), operator!(), operator&(), Inter::skip_variable(), NotCond::skip_variable(), Add::skip_variable(), Monotonic::skip_variable(), Compose::skip_variable(), RightConcat::skip_variable(), and Fixpoint::skip_variable().
const GHom::range_t _setVarConst::get_range () const inline virtual
The range returns the dual of skip_variable, default implem considers that all variables are affected by this homomorphism.
Reimplemented from _GHom.
References var.
GDDD StrongHom::has_image (const GDDD & d) const virtual inherited
Reimplemented from _GHom.
References GDDD::begin(), GDDD::end(), GDDD::null, GDDD::one, StrongHom::phi(), StrongHom::phiOne(), GDDD::top, and GDDD::variable().
GDDD _GHom::has_image_skip (const GDDD & d) const inherited
References GDDD::begin(), GDDD::end(), GHom::has_image(), _GHom::has_image(), GHom::id, GDDD::null, GDDD::one, _GHom::skip_variable(), GDDD::top, and GDDD::variable().
size_t _setVarConst::hash () const inline virtual
Hash key computation.
It is essential for good hash table operation that the spread of the keys be as good as possible. Also, fast hash key computation is a good design goal. Note that bad hash functions will yield more collisions, thus equality comparisons which may be quite costly.
Implements _GHom.
References ddd::int32_hash(), val, and var.
GHom _setVarConst::invert (const GDDD &) const inline virtual
returns the predescessor homomorphism, using pot to determine variable domains
Reimplemented from _GHom.
References GHom::add(), GDDD::begin(), computeDomain(), GDDD::end(), setVarConst(), val, var, and varEqState().
virtual bool _GHom::is_selector () const inline virtual inherited
The isSelector predicate indicates a homomorphism that only selects paths in the SDD (no modifications, no additions) Tagging with isSelector() allows to enable optimizations and makes the homomorphism eligible as "condition" in ITE construct.
Reimplemented in Fixpoint, Minus, And, Compose, Monotonic, Add, NotCond, _VarCompVar, Inter, Mult, DomExtract, _VarCompState, Constant, and Identity.
Referenced by _GHom::invert(), and GHom::is_selector().
virtual void _GHom::mark () const inline virtual inherited
For garbage collection. Used in first phase of garbage collection.
Reimplemented in MLHomAdapter, Fixpoint, Minus, RightConcat, LeftConcat, And, Compose, Monotonic, Add, NotCond, Inter, Mult, Apply2k, and Constant.
Referenced by GHom::mark().
GHom _GHom::negate () const virtual inherited
returns a negation of a selector homomorphism h, such that h.negate() (d) = d - h(d)
Reimplemented in And, Add, NotCond, Inter, _VarCompState, Constant, and Identity.
References _GHom::GHom.
Referenced by GHom::negate().
bool _GHom::operator< (const _GHom & h) const inherited
Ordering between _GHom. It is the chronological ordering of creation.
References _GHom::creation_counter.
bool _setVarConst::operator== (const StrongHom & h) const inline virtual
Comparator is pure virtual. Define a behavior in user homomorphisms.
Implements StrongHom.
References val, and var.
bool StrongHom::operator== (const _GHom & h) const virtual inherited
Comparator for unicity table.
Users should not use this. The behavior is to check for type mismatch (and return false if that is the case) or call specialized comparators of derived subclasses otherwise.
Implements _GHom.
GHom _setVarConst::phi (int var, int val) const inline virtual
Evaluation over an arbitrary arc of a SDD.
Parameters
var the index of the variable labeling the node.
val the value labeling the arc.
Returns
a homomorphism to apply on the successor node
Implements StrongHom.
References _GHom::GHom, GHom::id, val, and var.
GDDD _setVarConst::phiOne () const inline virtual
Evaluation over terminal GDDD::one.
Returns a constant DDD. A homomorphism that does not overload phiOne does not expect to meet the terminal during it's evaluation, therefore default behavior returns GDDD::top
Reimplemented from StrongHom.
References GDDD::one.
void _setVarConst::print (std::ostream & os) const inline virtual
pretty print
Reimplemented from StrongHom.
References GDDD::getvarName(), val, and var.
bool _setVarConst::skip_variable (int) const inline virtual
The skip_variable predicate indicates which variables are "don't care" with respect to this SHom.
This is defined as a StrongHom with : phi(var,val) { if (skip_variable(var)) return GShom(var, val, this); else { real behavior } }
Reimplemented from _GHom.
References var.
Member Data Documentation
int _setVarConst::val private
Referenced by hash(), invert(), operator==(), phi(), and print().
int _setVarConst::var private
Referenced by get_range(), hash(), invert(), operator==(), phi(), print(), and skip_variable().
The documentation for this class was generated from the following file:
Hom_Basic.cpp
Please comment this page and report errors about it on the RefDocComments page.