DDD: StrongMLShom Class Reference
StrongMLShom Class Reference abstract
#include <MLSHom.h>
Public Member Functions
bool operator== (const _MLShom &h) const
virtual bool operator== (const StrongMLShom &) const =0
SHomNodeMap eval (const GSDD &) const
virtual SHomHomMap phi (int var, const DataSet &val) const =0
User defined behavior is input through this function.
virtual SHomNodeMap phiOne () const =0
virtual bool shouldCache () const
test if caching should be done : default means should cache
virtual size_t hash () const =0
unique table trivia
virtual _MLShom * clone () const =0
Member Function Documentation
virtual _MLShom* _MLShom::clone () const pure virtual inherited
Implemented in nsMLShom::LeftConcat, nsMLShom::ConstantUp, nsMLShom::GShomAdapter, nsMLShom::Add, and nsMLShom::Identity.
SHomNodeMap StrongMLShom::eval (const GSDD & d) const virtual
Implements _MLShom.
References AdditiveMap< K, V, EqualKey >::add(), AdditiveMap< K, V, EqualKey >::begin(), GSDD::begin(), AdditiveMap< K, V, EqualKey >::end(), GSDD::end(), GShom::id, GSDD::null, GSDD::one, phi(), phiOne(), GSDD::top, and GSDD::variable().
virtual size_t _MLShom::hash () const pure virtual inherited
unique table trivia
Implemented in nsMLShom::LeftConcat, nsMLShom::ConstantUp, nsMLShom::GShomAdapter, nsMLShom::Add, and nsMLShom::Identity.
bool StrongMLShom::operator== (const _MLShom & h) const virtual
Implements _MLShom.
virtual bool StrongMLShom::operator== (const StrongMLShom &) const pure virtual
virtual SHomHomMap StrongMLShom::phi (int var, const DataSet & val) const pure virtual
User defined behavior is input through this function.
Referenced by eval().
virtual SHomNodeMap StrongMLShom::phiOne () const pure virtual
Referenced by eval().
virtual bool _MLShom::shouldCache () const inline virtual inherited
test if caching should be done : default means should cache
Reimplemented in nsMLShom::Identity.
The documentation for this class was generated from the following files:
MLSHom.h
MLSHom.cpp
Please comment this page and report errors about it on the RefDocComments page.