DDD: sns::And Class Reference
sns::And Class Reference
A commutative composition of n homomorphisms.
Public Types
typedef std::vector< GShom > parameters_t
typedef
parameters_t::const_iterator parameters_it
Public Member Functions
And (const parameters_t &p, int ref=0)
bool operator== (const _GShom &h) const
Comparator.
size_t hash () const
Hash key computation.
_GShom * clone () const
bool is_selector () const
The isSelector predicate indicates a homomorphism that only selects paths in the SDD (no modifications, no additions) Tagging with isSelector() allows to enable optimizations and makes the homomorphism eligible as "condition" in ITE construct.
bool skip_variable (int var) const
The skip_variable predicate indicates which variables are "don't care" with respect to this SHom.
const GShom::range_t get_range () const
The range returns the dual of skip_variable, default implem considers that all variables are affected by this homomorphism.
GSDD eval (const GSDD &d) const
The computation function responsible for evaluation over a node.
void mark () const
For garbage collection. Used in first phase of garbage collection.
GShom invert (const GSDD &pot) const
GSDD has_image (const GSDD &d) const
void print (std::ostream &os) const
GSDD has_image_skip (const GSDD &) const
virtual GShom compose (const GShom &) const
void mark_if_refd () const
void ref () const
void deref () const
unsigned long int refCounter () const
bool is_marked () const
void set_mark (bool val) const
Static Public Member Functions
static const _GShom * get_concret (const GShom &gshom)
TODO : this is a dirty trick to allow us to do terms rewriting in Add, Fixpoint etc...
Public Attributes
parameters_t parameters
PLEASE DONT HURT ME !!
Detailed Description
A commutative composition of n homomorphisms.
Member Typedef Documentation
typedef parameters_t::const_iterator sns::And::parameters_it
typedef std::vector<GShom> sns::And::parameters_t
Constructor & Destructor Documentation
sns::And::And (const parameters_t & p, int ref = 0) inline
Referenced by clone().
Member Function Documentation
_GShom* sns::And::clone () const inline virtual
Implements _GShom.
References And().
GShom _GShom::compose (const GShom & r) const virtual inherited
References GShom::id, and GSDD::null.
Referenced by GShom::compose().
void _GShom::deref () const inline inherited
References _GShom::_refCounter.
Referenced by Shom::operator=(), and Shom::~Shom().
GSDD sns::And::eval (const GSDD &) const inline virtual
The computation function responsible for evaluation over a node.
Users should not directly use this. Normal behavior is to use GShom::operator() that encapsulates this call with operation caching.
Implements _GShom.
References GShom::id, GSDD::null, GSDD::one, parameters, GSDD::top, and GSDD::variable().
static const _GShom* _GShom::get_concret (const GShom & gshom) inline static inherited
TODO : this is a dirty trick to allow us to do terms rewriting in Add, Fixpoint etc...
A more elegant architecture would be nice.
References GShom::concret.
Referenced by addCompositionParameter(), addParameter(), buildUnionParameters(), sns::RecFireSat::eval(), sns::Fixpoint::eval(), sns::Add::factorizeByLevel(), fixpoint(), GShom::GShom(), operator!(), operator&(), operator*(), sns::recFireSat(), sns::Inter::skip_variable(), sns::Add::skip_variable(), and sns::RightConcat::skip_variable().
const GShom::range_t sns::And::get_range () const inline virtual
The range returns the dual of skip_variable, default implem considers that all variables are affected by this homomorphism.
Reimplemented from _GShom.
References parameters.
GSDD sns::And::has_image (const GSDD & d) const inline virtual
Reimplemented from _GShom.
References GShom::has_image(), GShom::id, GSDD::null, GSDD::one, parameters, GSDD::top, and GSDD::variable().
GSDD _GShom::has_image_skip (const GSDD & d) const inherited
References GSDD::begin(), GSDD::end(), GShom::has_image(), _GShom::has_image(), GShom::id, GSDD::null, GSDD::one, _GShom::skip_variable(), GSDD::top, and GSDD::variable().
size_t sns::And::hash () const inline virtual
Hash key computation.
It is essential for good hash table operation that the spread of the keys be as good as possible. Also, fast hash key computation is a good design goal. Note that bad hash functions will yield more collisions, thus equality comparisons which may be quite costly.
Implements _GShom.
References parameters.
GShom sns::And::invert (const GSDD & pot) const inline virtual
Reimplemented from _GShom.
References GShom::id, and parameters.
bool _GShom::is_marked () const inline inherited
References _GShom::_refCounter.
Referenced by _GShom::set_mark().
bool sns::And::is_selector () const inline virtual
The isSelector predicate indicates a homomorphism that only selects paths in the SDD (no modifications, no additions) Tagging with isSelector() allows to enable optimizations and makes the homomorphism eligible as "condition" in ITE construct.
Reimplemented from _GShom.
References parameters.
void sns::And::mark () const inline virtual
For garbage collection. Used in first phase of garbage collection.
Reimplemented from _GShom.
References parameters.
void _GShom::mark_if_refd () const inline inherited
References _GShom::refCounter(), and _GShom::set_mark().
bool sns::And::operator== (const _GShom & h) const inline virtual
Comparator.
Used in case of hash collision. Should be appropriately defined in derived classes, in particular in user defined homomorphisms.
Implements _GShom.
References parameters.
void sns::And::print (std::ostream & os) const inline virtual
Implements _GShom.
References parameters.
void _GShom::ref () const inline inherited
References _GShom::_refCounter.
Referenced by Shom::operator=(), and Shom::Shom().
unsigned long int _GShom::refCounter () const inline inherited
References _GShom::_refCounter.
Referenced by _GShom::mark_if_refd(), Shom::operator=(), GShom::refCounter(), and Shom::~Shom().
void _GShom::set_mark (bool val) const inline inherited
References _GShom::_refCounter, _GShom::is_marked(), and _GShom::mark().
Referenced by GShom::garbage(), GShom::mark(), and _GShom::mark_if_refd().
bool sns::And::skip_variable (int) const inline virtual
The skip_variable predicate indicates which variables are "don't care" with respect to this SHom.
This is defined as a StrongHom with : phi(var,val) { if (skip_variable(var)) return GShom(var, val, this); else { real behavior } }
Reimplemented from _GShom.
References parameters.
Member Data Documentation
parameters_t sns::And::parameters
PLEASE DONT HURT ME !!
Referenced by eval(), get_range(), has_image(), hash(), invert(), is_selector(), mark(), operator==(), print(), and skip_variable().
The documentation for this class was generated from the following file:
SHom.cpp
Please comment this page and report errors about it on the RefDocComments page.