DDD: Shom Class Reference
Shom Class Reference
This is the user interface class to manipulate homomorphisms.
#include <SHom.h>
Public Types
enum fixpointStrategy { BFS, DFS }
enum saturationStrategy { ORDINARY, RECFIREANDSAT }
typedef GSDD NodeType
Public Member Functions
GShom invert (const GSDD &pot) const
returns the predescessor homomorphism, using pot to determine variable domains
GSDD has_image (const GSDD &d) const
returns true if and only if h(d) != SDD::null
GShom compose (const GShom &) const
int refCounter () const
For debug and development purposes. Gives the reference count of the concrete data.
Public Constructors.
Default constructor builds identity homomorphism.
Shom (const GShom &h=GShom::id)
Build an Shom from a GShom.
Shom (const Shom &h)
Copy constructor. Maintains reference count.
Shom (const GSDD &d)
Constructs a constant homomorphism.
Shom (int var, const DataSet &val, const GShom &h=GShom::id)
Left concatenation of a single arc SDD.
~Shom ()
Destructor maintains reference counting.
Assignment operators.
Shom & operator= (const GShom &)
Overloaded behavior for assignment operator, maintains reference counting.
Shom & operator= (const Shom &)
Overloaded behavior for assignment operator, maintains reference counting.
Evaluation mechanism for homomorphisms.
GSDD operator() (const GSDD &d) const
Applying a homomorphism to a node returns a node.
GSDD eval (const GSDD &d) const
The full evaluation, this is the computational procedure, that is called when the computation cache yields a miss.
Static Public Member Functions
static GShom add (const d3::set< GShom >::type &s)
Compute an n-ary sum between homomorphisms.
static fixpointStrategy getFixpointStrategy ()
static void setFixpointStrategy (fixpointStrategy strat)
static saturationStrategy getSaturationStrategy ()
static void setSaturationStrategy (saturationStrategy strat)
Static Public Attributes
static const Shom null = GSDD::null
static const GShom id
Elementary SDD homomorphism identity. Applied to any SDD d, it returns d.
Comparisons between GShom.
Comparisons between GShom for unicity table.
Both equality comparison and total ordering provided to allow hash and map storage of GShom
static const range_t full_range = GShom::range_t()
The full_range : that targets everyone.
bool operator== (const GShom &h) const
bool operator!= (const GShom &h) const
bool operator< (const GShom &h) const
bool is_selector () const
This predicate is true if the homomorphism global behavior is only to prune some paths.
bool skip_variable (int) const
This predicate is true if the homomorphism "skips" this variable.
const range_t get_range () const
Returns the range for this homomorphism, i.e. the dual of skip_variable.
typedef d3::set< int >::type range_t
typedef range_t::const_iterator range_it
Memory Management routines.
void mark () const
Mark a concrete data as in use (forbids garbage collection of the data).
size_t hash () const
For storage in a hash table.
static unsigned int statistics ()
Return the current size of the unicity table for GShom.
static size_t cache_size ()
Return the current size of the cache for GShom.
static size_t cache_peak ()
Return the peak size of the cache for GShom.
static void pstats (bool reinit=true)
Print some usage statistics on Shom.
static void garbage ()
Collects and destroys unused homomorphisms.
Detailed Description
This is the user interface class to manipulate homomorphisms.
The only difference with GShom is that it implements reference counting so that instances of Shom are not collected upon MemoryManager::garbage().
Member Typedef Documentation
typedef GSDD GShom::NodeType inherited
typedef range_t::const_iterator GShom::range_it inherited
typedef d3::set<int>::type GShom::range_t inherited
Member Enumeration Documentation
enum GShom::fixpointStrategy inherited
Enumerator
BFS
DFS
enum GShom::saturationStrategy inherited
Enumerator
ORDINARY
RECFIREANDSAT
Constructor & Destructor Documentation
Shom::Shom (const GShom & h = GShom::id)
Build an Shom from a GShom.
References GShom::concret, and _GShom::ref().
Shom::Shom (const Shom & h)
Copy constructor. Maintains reference count.
References GShom::concret, and _GShom::ref().
Shom::Shom (const GSDD & d)
Constructs a constant homomorphism.
References GShom::concret, and _GShom::ref().
Shom::Shom (int var, const DataSet & val, const GShom & h = GShom::id)
Left concatenation of a single arc SDD.
This is provided as a convenience and to avoid the inefficiency if we build a node pointing to GSDD::one and then concatenate something to it. Applied to a SDD d, this homomorphism will return var–val->h(d).
Parameters
var the variable labeling the node to left concat
val the set of values labeling the arc
h the homomorphism to apply on the argument d. This defaults to GSHom::id.
References GShom::concret, and _GShom::ref().
Shom::~Shom ()
Destructor maintains reference counting.
Note that the destructor does not truly reclaim memory, MemoryManager::garbage() does that.
References GShom::concret, _GShom::deref(), and _GShom::refCounter().
Member Function Documentation
static GShom GShom::add (const d3::set< GShom >::type & s) static inherited
Compute an n-ary sum between homomorphisms.
This should be slightly more efficient in evaluation than a composition of binary sums constructed using the friend operator+.
Todo:
: move this to friend status not static member for more homogeneity with other operators.
size_t GShom::cache_peak () static inherited
Return the peak size of the cache for GShom.
References sns::cache, and Cache< FuncType, ParamType, ResType, EvalFunc >::peak().
size_t GShom::cache_size () static inherited
Return the current size of the cache for GShom.
References sns::cache, and Cache< FuncType, ParamType, ResType, EvalFunc >::size().
Referenced by Statistic::load().
GShom GShom::compose (const GShom & o) const inherited
References _GShom::compose(), and GShom::concret.
Referenced by operator&().
GSDD GShom::eval (const GSDD & d) const inherited
The full evaluation, this is the computational procedure, that is called when the computation cache yields a miss.
Users should not use this function directly, but only through GSDD::operator().
References GShom::concret, and _GShom::eval_skip().
Referenced by _SDED_Shom::eval(), and GShom::operator()().
void GShom::garbage () static inherited
Collects and destroys unused homomorphisms.
Do not call this directly but through MemoryManager::garbage() as order of calls (among GSDD::garbage(), GShom::garbage(), SDED::garbage()) is important.
References sns::cache, canonical, Cache< FuncType, ParamType, ResType, EvalFunc >::clear(), sns::imgcache, and _GShom::set_mark().
Referenced by MemoryManager::garbage().
const GShom::range_t GShom::get_range () const inherited
Returns the range for this homomorphism, i.e. the dual of skip_variable.
References GShom::concret, and _GShom::get_range().
Referenced by commutative(), fixpoint(), sns::SNotCond::get_range(), sns::RecFireSat::get_range(), sns::Compose::get_range(), sns::Fixpoint::get_range(), and notInRange().
static fixpointStrategy GShom::getFixpointStrategy () inline static inherited
References GShom::fixpointStrategy_.
Referenced by sns::Fixpoint::eval().
static saturationStrategy GShom::getSaturationStrategy () inline static inherited
References GShom::saturationStrategy_.
Referenced by sns::Fixpoint::eval().
GSDD GShom::has_image (const GSDD & d) const inherited
returns true if and only if h(d) != SDD::null
References sns::imgcache, and GSDD::null.
Referenced by sns::RecFireSat::eval(), sns::Inter::has_image(), sns::SLocalApply::has_image(), sns::SNotCond::has_image(), sns::And::has_image(), sns::Compose::has_image(), sns::LeftConcat::has_image(), sns::RightConcat::has_image(), and _GShom::has_image_skip().
size_t GShom::hash () const inline inherited
For storage in a hash table.
References GShom::concret, and ddd::knuth32_hash().
Referenced by nsMLShom::GShomAdapter::hash(), nsMLShom::ConstantUp::hash(), sns::Mult::hash(), sns::Inter::hash(), sns::SLocalApply::hash(), _SDED_Shom::hash(), sns::SNotCond::hash(), sns::RecFireSat::hash(), sns::Compose::hash(), sns::LeftConcat::hash(), sns::RightConcat::hash(), sns::Minus::hash(), sns::HomMinus::hash(), and sns::Fixpoint::hash().
GShom GShom::invert (const GSDD & pot) const inherited
returns the predescessor homomorphism, using pot to determine variable domains
References GShom::concret, and _GShom::invert().
Referenced by sns::Mult::invert(), sns::Inter::invert(), sns::SLocalApply::invert(), sns::RecFireSat::invert(), sns::Compose::invert(), sns::Minus::invert(), sns::HomMinus::invert(), and sns::Fixpoint::invert().
bool GShom::is_selector () const inherited
This predicate is true if the homomorphism global behavior is only to prune some paths.
References GShom::concret, and _GShom::is_selector().
Referenced by commutative(), fixpoint(), sns::Mult::is_selector(), sns::Inter::is_selector(), sns::SLocalApply::is_selector(), sns::RecFireSat::is_selector(), sns::Compose::is_selector(), sns::Minus::is_selector(), sns::HomMinus::is_selector(), sns::Fixpoint::is_selector(), ITE(), operator!(), and operator*().
void GShom::mark () const inherited
Mark a concrete data as in use (forbids garbage collection of the data).
References GShom::concret, and _GShom::set_mark().
Referenced by sns::Fixpoint::eval(), sns::Mult::mark(), sns::Inter::mark(), sns::SLocalApply::mark(), sns::SNotCond::mark(), sns::RecFireSat::mark(), sns::Compose::mark(), sns::LeftConcat::mark(), sns::RightConcat::mark(), sns::Minus::mark(), sns::HomMinus::mark(), and sns::Fixpoint::mark().
bool GShom::operator!= (const GShom & h) const inline inherited
References GShom::concret.
GSDD GShom::operator() (const GSDD & d) const inherited
Applying a homomorphism to a node returns a node.
This is the normal way for users of computing the application of a homomorphism.
References sns::cache, GShom::concret, GShom::eval(), _GShom::immediat(), and GSDD::null.
bool GShom::operator< (const GShom & h) const inline inherited
References GShom::concret.
Shom & Shom::operator= (const GShom & h)
Overloaded behavior for assignment operator, maintains reference counting.
References GShom::concret, _GShom::deref(), _GShom::ref(), and _GShom::refCounter().
Shom & Shom::operator= (const Shom & h)
Overloaded behavior for assignment operator, maintains reference counting.
References GShom::concret, _GShom::deref(), _GShom::ref(), and _GShom::refCounter().
bool GShom::operator== (const GShom & h) const inline inherited
References GShom::concret.
void GShom::pstats (bool reinit = true) static inherited
Print some usage statistics on Shom.
Mostly used for development and debug.
Todo:
Allow output not in std::cout.
References GShom::_GShom, sns::cache, and canonical.
Referenced by MemoryManager::pstats().
int GShom::refCounter () const inherited
For debug and development purposes. Gives the reference count of the concrete data.
References GShom::concret, and _GShom::refCounter().
static void GShom::setFixpointStrategy (fixpointStrategy strat) inline static inherited
References GShom::fixpointStrategy_.
static void GShom::setSaturationStrategy (saturationStrategy strat) inline static inherited
References GShom::saturationStrategy_.
bool GShom::skip_variable (int var) const inherited
This predicate is true if the homomorphism "skips" this variable.
References GShom::concret, and _GShom::skip_variable().
Referenced by sns::Mult::eval(), nsMLShom::GShomAdapter::skip_variable(), sns::SNotCond::skip_variable(), sns::RecFireSat::skip_variable(), sns::Compose::skip_variable(), and sns::Fixpoint::skip_variable().
unsigned int GShom::statistics () static inherited
Return the current size of the unicity table for GShom.
References canonical.
Referenced by Statistic::load(), and MemoryManager::nbShom().
Member Data Documentation
const GShom::range_t GShom::full_range = GShom::range_t() static inherited
The full_range : that targets everyone.
Referenced by _GShom::get_range().
const GShom GShom::id static inherited
Elementary SDD homomorphism identity. Applied to any SDD d, it returns d.
Referenced by apply2k(), buildUnionParameters(), _GShom::compose(), nsMLShom::Identity::eval(), nsMLShom::GShomAdapter::eval(), StrongMLShom::eval(), sns::Mult::eval(), sns::And::eval(), sns::Fixpoint::eval(), _GShom::eval_skip(), fixpoint(), sns::And::has_image(), _GShom::has_image_skip(), sns::Mult::invert(), sns::And::invert(), sns::Minus::invert(), sns::HomMinus::invert(), sns::Fixpoint::invert(), localApply(), operator!(), operator&(), and operator*().
const Shom Shom::null = GSDD::null static
Referenced by GShom::GShom(), _GShom::invert(), localApply(), operator!(), operator&(), and operator*().
The documentation for this class was generated from the following files:
SHom.h
SDD.cpp
SHom.cpp
Please comment this page and report errors about it on the RefDocComments page.