DDD: _GSDD Class Reference
_GSDD Class Reference
Public Member Functions
_GSDD (int var, int cpt=0)
_GSDD (int var, GSDD::Valuation val, int cpt=0)
virtual ~_GSDD ()
_GSDD (const _GSDD &g)
_GSDD * clone () const
bool operator< (const _GSDD &g) const
bool operator== (const _GSDD &g) const
void mark () const
size_t hash () const
void mark_if_refd () const
void ref () const
void deref () const
unsigned long int refCounter () const
bool is_marked () const
void set_mark (bool val) const
Public Attributes
const int variable
GSDD::Valuation valuation
unsigned long int _refCounter
Constructor & Destructor Documentation
_GSDD::_GSDD (int var, int cpt = 0) inline
Referenced by clone().
_GSDD::_GSDD (int var, GSDD::Valuation val, int cpt = 0) inline
References valsorter(), and valuation.
virtual _GSDD::~_GSDD () inline virtual
References valuation.
_GSDD::_GSDD (const _GSDD & g) inline
References valuation.
Member Function Documentation
_GSDD* _GSDD::clone () const inline
References _GSDD().
void _GSDD::deref () const inline
References _refCounter.
Referenced by SDD::operator=(), and SDD::~SDD().
size_t _GSDD::hash () const inline
References valuation, and variable.
bool _GSDD::is_marked () const inline
References _refCounter.
Referenced by mark().
void _GSDD::mark () const
References is_marked(), set_mark(), and valuation.
Referenced by GSDD::mark(), and mark_if_refd().
void _GSDD::mark_if_refd () const inline
References mark(), and refCounter().
bool _GSDD::operator< (const _GSDD & g) const inline
References valuation, and variable.
bool _GSDD::operator== (const _GSDD & g) const inline
References valuation, and variable.
void _GSDD::ref () const inline
References _refCounter.
Referenced by SDD::operator=(), and SDD::SDD().
unsigned long int _GSDD::refCounter () const inline
References _refCounter.
Referenced by mark_if_refd(), GSDD::refCounter(), and SDD::~SDD().
void _GSDD::set_mark (bool val) const inline
References _refCounter.
Referenced by GSDD::garbage(), and mark().
Member Data Documentation
unsigned long int _GSDD::_refCounter mutable
Referenced by deref(), is_marked(), ref(), refCounter(), and set_mark().
GSDD::Valuation _GSDD::valuation
Referenced by _GSDD(), GSDD::begin(), GSDD::end(), GSDD::GSDD(), hash(), mark(), GSDD::nbsons(), operator<(), operator==(), and ~_GSDD().
const int _GSDD::variable
Referenced by hash(), operator<(), operator==(), and GSDD::variable().
The documentation for this class was generated from the following file:
SDD.cpp
Please comment this page and report errors about it on the RefDocComments page.