DDD: _GDDD Class Reference
_GDDD Class Reference
Classes
struct custom_new_t
an empty struct tag type used to disambiguate between different variants of the operator new for _GDDD.
Public Member Functions
~_GDDD ()
destructor
const_iterator begin () const
iterator API
const_iterator end () const
bool operator== (const _GDDD &g) const
bool operator< (const _GDDD &g) const
size_t hash () const
hash
void mark () const
Memory Manager and reference counting.
_GDDD * clone () const
cloning
Static Public Member Functions
static GDDD::id_t create_unique_GDDD (int var, const GDDD::Valuation &val)
factory operation
static const _GDDD * resolve (GDDD::id_t id)
static void operator delete (void *addr)
custom operator delete
Private Types
typedef GDDD::edge_t edge_t
useful typedefs
typedef GDDD::const_iterator const_iterator
Private Member Functions
edge_t * alpha_addr () const
get the address of the valuation
_GDDD (int var, const GDDD::Valuation &val)
constructor
template<class Iterator >
_GDDD (int var, Iterator begin, Iterator end)
constructor (with iterators)
_GDDD (const _GDDD &)=delete
cannot copy or move these four operations are deliberately private and UNIMPLEMENTED
_GDDD & operator= (const _GDDD &)=delete
_GDDD (_GDDD &&)=delete
_GDDD & operator= (_GDDD &&)=delete
Static Private Member Functions
static void * operator new (size_t, custom_new_t, size_t length)
custom operator new WARNING: the expected arguments are not standard
static void * operator new (size_t, void *addr)
classical placement new NB: it is the responsibility of the caller that there is enough room to build the _GDDD.
Private Attributes
const int variable
attributes
const unsigned short valuation_size
Friends
class GDDD
void saveDDD (std::ostream &, std::vector< DDD >)
Member Typedef Documentation
typedef GDDD::const_iterator _GDDD::const_iterator private
typedef GDDD::edge_t _GDDD::edge_t private
useful typedefs
Constructor & Destructor Documentation
_GDDD::_GDDD (int var, const GDDD::Valuation & val) inline private
constructor
Referenced by alpha_addr(), and operator new().
template<class Iterator > _GDDD::_GDDD (int var, Iterator begin, Iterator end) inline private
constructor (with iterators)
References alpha_addr().
_GDDD::_GDDD (const _GDDD &) private delete
cannot copy or move these four operations are deliberately private and UNIMPLEMENTED
_GDDD::_GDDD (_GDDD &&) private delete
_GDDD::~_GDDD () inline
destructor
References begin(), and end().
Referenced by create_unique_GDDD().
Member Function Documentation
edge_t* _GDDD::alpha_addr () const inline private
get the address of the valuation
References _GDDD().
Referenced by _GDDD(), begin(), and end().
const_iterator _GDDD::begin () const inline
iterator API
References alpha_addr().
Referenced by GDDD::begin(), clone(), hash(), mark(), operator<(), operator==(), and ~_GDDD().
_GDDD* _GDDD::clone () const inline
cloning
References begin(), end(), valuation_size, and variable.
static GDDD::id_t _GDDD::create_unique_GDDD (int var, const GDDD::Valuation & val) inline static
factory operation
References UniqueTableId< T, ID >::instance(), and ~_GDDD().
Referenced by GDDD::GDDD().
const_iterator _GDDD::end () const inline
References alpha_addr(), and valuation_size.
Referenced by clone(), GDDD::end(), hash(), mark(), operator<(), operator==(), and ~_GDDD().
size_t _GDDD::hash () const inline
hash
References begin(), end(), ddd::int32_hash(), variable, and ddd::wang32_hash().
void _GDDD::mark () const inline
Memory Manager and reference counting.
References begin(), and end().
static void _GDDD::operator delete (void * addr) inline static
custom operator delete
static void* _GDDD::operator new (size_t , custom_new_t , size_t length) inline static private
custom operator new WARNING: the expected arguments are not standard
the first one (actually sizeof(_GDDD)) is ignored
the second one is 'custom_new_t', for disambiguation
the third one is the number of successors syntax: new (custom_new_t(), nb_sons) _GDDD (constructor arguments) it looks like a placement new, but this syntax is only used to pass arguments to operator new _GDDD should only be constructed by create_unique_GDDD or clone please refer to these two functions for invokation examples
References _GDDD().
static void* _GDDD::operator new (size_t , void * addr) inline static private
classical placement new NB: it is the responsibility of the caller that there is enough room to build the _GDDD.
e.g. new (ad) _GDDD(v, val) the memory chunk at 'ad' must be of size at least sizeof(_GDDD)+sizeof(edge_t)*val.size()
bool _GDDD::operator< (const _GDDD & g) const inline
References begin(), end(), valuation_size, and variable.
_GDDD& _GDDD::operator= (const _GDDD &) private delete
_GDDD& _GDDD::operator= (_GDDD &&) private delete
bool _GDDD::operator== (const _GDDD & g) const inline
References begin(), end(), valuation_size, and variable.
static const _GDDD* _GDDD::resolve (GDDD::id_t id) inline static
References UniqueTableId< T, ID >::instance(), and UniqueTableId< T, ID >::resolve().
Referenced by GDDD::begin(), GDDD::end(), GDDD::nbsons(), and GDDD::variable().
Friends And Related Function Documentation
friend class GDDD friend
void saveDDD (std::ostream & os, std::vector< DDD > list) friend
Member Data Documentation
const unsigned short _GDDD::valuation_size private
Referenced by clone(), end(), GDDD::nbsons(), operator<(), and operator==().
const int _GDDD::variable private
attributes
Referenced by clone(), hash(), operator<(), operator==(), and GDDD::variable().
The documentation for this class was generated from the following file:
DDD.cpp
Please comment this page and report errors about it on the RefDocComments page.