DDD: nsMLShom::LeftConcat Class Reference
nsMLShom::LeftConcat Class Reference
Public Member Functions
LeftConcat (const GSDD &l, const MLShom &_h, int ref=0)
bool operator== (const _MLShom &other) const
_MLShom * clone () const
size_t hash () const
unique table trivia
bool skip_variable (int) const
SHomNodeMap eval (const GSDD &d) const
virtual bool shouldCache () const
test if caching should be done : default means should cache
Private Attributes
GSDD left
MLShom h
Constructor & Destructor Documentation
nsMLShom::LeftConcat::LeftConcat (const GSDD & l, const MLShom & _h, int ref = 0) inline
Referenced by clone().
Member Function Documentation
_MLShom* nsMLShom::LeftConcat::clone () const inline virtual
Implements _MLShom.
References LeftConcat().
SHomNodeMap nsMLShom::LeftConcat::eval (const GSDD & d) const inline virtual
Implements _MLShom.
References AdditiveMap< K, V, EqualKey >::add(), AdditiveMap< K, V, EqualKey >::begin(), AdditiveMap< K, V, EqualKey >::end(), h, and left.
size_t nsMLShom::LeftConcat::hash () const inline virtual
unique table trivia
Implements _MLShom.
References h, MLShom::hash(), GSDD::hash(), and left.
bool nsMLShom::LeftConcat::operator== (const _MLShom & other) const inline virtual
Implements _MLShom.
References h, and left.
virtual bool _MLShom::shouldCache () const inline virtual inherited
test if caching should be done : default means should cache
Reimplemented in nsMLShom::Identity.
bool nsMLShom::LeftConcat::skip_variable (int) const inline
Member Data Documentation
MLShom nsMLShom::LeftConcat::h private
Referenced by eval(), hash(), and operator==().
GSDD nsMLShom::LeftConcat::left private
Referenced by eval(), hash(), and operator==().
The documentation for this class was generated from the following file:
MLSHom.cpp
Please comment this page and report errors about it on the RefDocComments page.