DDD: SDD Class Reference
SDD Class Reference
This class is the public interface for manipulating Data Decision Diagrams.
#include <SDD.h>
Public Member Functions
SDD (const SDD &)
Copy constructor.
SDD (const GSDD &g=GSDD::null)
Copy constructor from base class GDDD, also default DDD constructor to empty set.
SDD (int var, const DataSet &val, const GSDD &d=one)
The most common way for the user of creating DDD.
SDD (int var, const GSDD &val, const GSDD &d=one)
SDD (int var, const SDD &val, const GSDD &d=one)
virtual ~SDD ()
Destructor, maintains refCount.
unsigned int refCounter () const
Returns current reference count of a node.
unsigned long int size () const
Returns the size in number of nodes of a SDD structure.
std::pair< unsigned long int,
unsigned long int > node_size () const
size_t nbsons () const
Returns the number of successors of a given node. This is the size of the arc array of the node.
long double nbStates () const
Returns the number of states or paths represented by a given node.
Assignment operators.
SDD & operator= (const GSDD &)
Overloaded behavior for assignment operator, maintains reference counting.
SDD & operator= (const SDD &)
Overloaded behavior for assignment operator, maintains reference counting.
Comparisons for hash and map storage
bool operator== (const GSDD &g) const
Comparison between DDD.
bool operator!= (const GSDD &g) const
Comparison between DDD.
bool operator< (const GSDD &g) const
Total ordering function between DDD.
DataSet implementation interface
This is the implementation of the DataSet class interface used in SDD context.
These functions allow to reference SDD from SDD arcs. IMPORTANT Remember to delete returned values after use.
Note these functions are not resistant to incompatible DataSet types. When these functions have a parameter "b", it should be a reference to a SDD from proper behavior.
DataSet * newcopy () const
Return a new copy of a SDD.
DataSet * set_intersect (const DataSet &b) const
Compute intersection of two SDD.
DataSet * set_union (const DataSet &b) const
Compute union of two SDD.
DataSet * set_minus (const DataSet &b) const
Compute set difference of two SDD.
bool empty () const
Return true if this is the empty set.
DataSet * empty_set () const
Returns a pointer to GSDD::null.
bool set_equal (const DataSet &b) const
Compares to DataSet for equality.
bool set_less_than (const DataSet &b) const
Compares two sets with a total order.
long double set_size () const
Compares to DataSet for equality.
size_t set_hash () const
Returns a hash key for the SDD.
void set_print (std::ostream &os) const
Textual (human readable) output of a SDD.
Static Public Attributes
Terminal nodes defined as constants
static const GSDD one
The accepting terminal. This is the basic leaf for accepted sequences.
static const GSDD null
The non-accepting terminal.
static const GSDD top
The approximation terminal.
Public Accessors
int variable () const
Returns a node's variable.
const_iterator begin () const
API for iterating over the arcs of a DDD manually.
const_iterator end () const
API for iterating over the arcs of a DDD manually.
typedef std::vector< std::pair
< DataSet *, GSDD > > Valuation
To hide how arcs are actually stored. Use GSDD::Valuation to refer to arcs type.
typedef Valuation::const_iterator const_iterator
To hide how arcs are stored.
Memory Management
Broken right now, dont use me or fixme first Returns the number of nodes that would be used to represent a SDD if no unicity table was used.
void mark () const
For garbage collection internals.
size_t hash () const
For storage in a hash table.
static unsigned int statistics ()
Returns unicity table current size. Gives the number of different nodes created and not yet destroyed.
static void garbage ()
For garbage collection, do not call this directly, use MemoryManager::garbage() instead.
static void pstats (bool reinit=true)
Prints some statistics to std::cout.
static size_t peak ()
Returns the peak size of the DDD unicity table. This value is maintained up to date upon GarbageCollection.
Detailed Description
This class is the public interface for manipulating Data Decision Diagrams.
Except when defining new homomorphisms, a user of the library should only manipulate SDD, not GSDD. Reference counting is enabled for SDD, so they will not be destroyed if they are still in use upon garbage collection.
Member Typedef Documentation
typedef Valuation::const_iterator GSDD::const_iterator inherited
To hide how arcs are stored.
Also for more compact expressions : use GDDD::const_iterator to iterate over the arcs of a DDD
typedef std::vector<std::pair<DataSet *,GSDD> > GSDD::Valuation inherited
To hide how arcs are actually stored. Use GSDD::Valuation to refer to arcs type.
Constructor & Destructor Documentation
SDD::SDD (const SDD & g)
Copy constructor.
Constructs a copy, actual data (concret) is not copied. RefCounter is updated however.
References GSDD::concret, and _GSDD::ref().
SDD::SDD (const GSDD & g = GSDD::null)
Copy constructor from base class GDDD, also default DDD constructor to empty set.
Increments refCounter of g.concret.
References GSDD::concret, and _GSDD::ref().
SDD::SDD (int var, const DataSet & val, const GSDD & d = one)
The most common way for the user of creating DDD.
This constructor builds a node with a single arc of the form var-val->d. Usually a user will create these single path DDD, possibly by imbrication as in SDD(var1, val1, SDD(var2, val2)). Then compose them using +, -, *, ^ ... See also GSDD(var,val,d).
Parameters
var the variable labeling the node
val the value labeling the arc
d the successor node or defaults to terminal GDDD::one if none provided
References GSDD::concret, and _GSDD::ref().
SDD::SDD (int var, const GSDD & val, const GSDD & d = one)
References GSDD::concret, and _GSDD::ref().
SDD::SDD (int var, const SDD & val, const GSDD & d = one)
References GSDD::concret, and _GSDD::ref().
SDD::~SDD () virtual
Destructor, maintains refCount.
Note that destroying a DDD does not actually destroy any data, it decrements reference count, so that subsequent MemoryManager::garbage call may truly clear the data.
References GSDD::concret, _GSDD::deref(), and _GSDD::refCounter().
Member Function Documentation
GSDD::const_iterator GSDD::begin () const inherited
API for iterating over the arcs of a DDD manually.
i.e. not using a predefined evaluation mechanism such as StrongHom
for (GDDD::const_iterator it = a_gddd.begin() ; it != a_gddd.end() ; it++) { // do something }
returns the first arc
References GSDD::concret, and _GSDD::valuation.
Referenced by dotExporter::collect(), hDotExporter::collect(), StrongMLShom::eval(), sns::SApply2k::eval(), sns::Mult::eval(), _SDED_Mult::eval(), sns::SDomExtract::eval(), _SDED_Minus::eval(), sns::LocalApply::eval(), StrongShom::eval(), _SDED_Concat::eval(), sns::SLocalApply::eval(), sns::RecFireSat::eval(), _GShom::eval_skip(), sns::LocalApply::has_image(), StrongShom::has_image(), sns::SLocalApply::has_image(), _GShom::has_image_skip(), sns::LocalApply::invert(), sns::SLocalApply::invert(), MySDDNbStates::nbStates(), GSDD::print(), dotExporter::printColor(), and SddSize::sddsize().
bool GSDD::empty () const virtual inherited
Return true if this is the empty set.
Implements DataSet.
References GSDD::null.
Referenced by GSDD::GSDD().
DataSet * GSDD::empty_set () const virtual inherited
Returns a pointer to GSDD::null.
Implements DataSet.
References GSDD::GSDD().
GSDD::const_iterator GSDD::end () const inherited
API for iterating over the arcs of a DDD manually.
i.e. not using a predefined evaluation mechanism such as StrongHom
for (GDDD::const_iterator it = a_gddd.begin() ; it != a_gddd.end() ; it++) { // do something }
returns a past the end iterator
References GSDD::concret, and _GSDD::valuation.
Referenced by dotExporter::collect(), hDotExporter::collect(), StrongMLShom::eval(), sns::SApply2k::eval(), sns::Mult::eval(), _SDED_Mult::eval(), sns::SDomExtract::eval(), _SDED_Minus::eval(), sns::LocalApply::eval(), StrongShom::eval(), _SDED_Concat::eval(), sns::SLocalApply::eval(), sns::RecFireSat::eval(), _GShom::eval_skip(), sns::LocalApply::has_image(), StrongShom::has_image(), sns::SLocalApply::has_image(), _GShom::has_image_skip(), MySDDNbStates::nbStates(), GSDD::print(), dotExporter::printColor(), and SddSize::sddsize().
void GSDD::garbage () static inherited
For garbage collection, do not call this directly, use MemoryManager::garbage() instead.
Todo:
describe garbage collection algorithm(s) + mark usage homogeneously in one place.
References MySDDNbStates::clear(), Max_SDD, _GSDD::set_mark(), UniqueTable< T >::size(), and UniqueTable< T >::table.
Referenced by MemoryManager::garbage().
size_t GSDD::hash () const inline inherited
For storage in a hash table.
References GSDD::concret, and ddd::knuth32_hash().
Referenced by _SDED_Mult::create(), _SDED_GSDD::hash(), sns::Constant::hash(), nsMLShom::LeftConcat::hash(), sns::SApply2k::hash(), sns::Mult::hash(), _SDED_Mult::hash(), _SDED_Minus::hash(), _SDED_Concat::hash(), _SDED_Shom::hash(), sns::LeftConcat::hash(), sns::RightConcat::hash(), and sns::Minus::hash().
void GSDD::mark () const virtual inherited
For garbage collection internals.
Marks a GSDD as in use in garbage collection phase.
Implements DataSet.
References GSDD::concret, and _GSDD::mark().
Referenced by sns::Fixpoint::eval(), sns::Constant::mark(), sns::SApply2k::mark(), sns::Mult::mark(), sns::LeftConcat::mark(), sns::RightConcat::mark(), and sns::Minus::mark().
size_t GSDD::nbsons () const inherited
Returns the number of successors of a given node. This is the size of the arc array of the node.
References GSDD::concret, and _GSDD::valuation.
Referenced by _GShom::eval_skip().
long double GSDD::nbStates () const inherited
Returns the number of states or paths represented by a given node.
Referenced by Statistic::load(), and GSDD::set_size().
DataSet* GSDD::newcopy () const inline virtual inherited
Return a new copy of a SDD.
Implements DataSet.
References GSDD::GSDD().
Referenced by GSDD::GSDD().
std::pair< unsigned long int, unsigned long int > GSDD::node_size () const inherited
References SddSize::d3res, and SddSize::res.
Referenced by Statistic::load().
bool GSDD::operator!= (const GSDD & g) const inline inherited
Comparison between DDD.
Note that comparison is based on "concret" address in unicity table.
Parameters
g the node to compare to
Returns
true if the nodes are not equal.
References GSDD::concret.
bool GSDD::operator< (const GSDD & g) const inherited
Total ordering function between DDD.
Note that comparison is based on "concret" address in unicity table. This ordering is necessary for hash and map storage of GDDD.
Parameters
g the node to compare to
Returns
true if argument g is greater than "this" node.
References GSDD::concret.
SDD & SDD::operator= (const GSDD & g)
Overloaded behavior for assignment operator, maintains reference counting.
References GSDD::concret, _GSDD::deref(), and _GSDD::ref().
SDD & SDD::operator= (const SDD & g)
Overloaded behavior for assignment operator, maintains reference counting.
References GSDD::concret, _GSDD::deref(), and _GSDD::ref().
bool GSDD::operator== (const GSDD & g) const inline inherited
Comparison between DDD.
Note that comparison is based on "concret" address in unicity table.
Parameters
g the node to compare to
Returns
true if the nodes are equal.
size_t GSDD::peak () static inherited
Returns the peak size of the DDD unicity table. This value is maintained up to date upon GarbageCollection.
References Max_SDD, and UniqueTable< T >::size().
Referenced by Statistic::load(), and GSDD::pstats().
void GSDD::pstats (bool reinit = true) static inherited
Prints some statistics to std::cout.
Mostly used in debug and development phase. See also MemoryManager::pstats().
Todo:
allow output in other place than cout. Clean up output.
References GSDD::_GSDD, GSDD::peak(), and UniqueTable< T >::size().
Referenced by MemoryManager::pstats().
unsigned int GSDD::refCounter () const inherited
Returns current reference count of a node.
Reference count corresponds to the number of SDD that use a given concrete node. No recursive reference counting is used : son nodes may have refCount=0 even if this node has a positive refCounter.
References GSDD::concret, and _GSDD::refCounter().
Referenced by dotExporter::collect().
bool GSDD::set_equal (const DataSet & b) const virtual inherited
Compares to DataSet for equality.
Implements DataSet.
size_t GSDD::set_hash () const virtual inherited
Returns a hash key for the SDD.
Implements DataSet.
References GSDD::concret.
DataSet * GSDD::set_intersect (const DataSet & b) const virtual inherited
Compute intersection of two SDD.
Implements DataSet.
References GSDD::GSDD().
bool GSDD::set_less_than (const DataSet & b) const virtual inherited
Compares two sets with a total order.
Implements DataSet.
DataSet * GSDD::set_minus (const DataSet & b) const virtual inherited
Compute set difference of two SDD.
Implements DataSet.
References GSDD::GSDD().
void GSDD::set_print (std::ostream & os) const inline virtual inherited
Textual (human readable) output of a SDD.
Implements DataSet.
long double GSDD::set_size () const virtual inherited
Compares to DataSet for equality.
Implements DataSet.
References GSDD::nbStates().
DataSet * GSDD::set_union (const DataSet & b) const virtual inherited
Compute union of two SDD.
Implements DataSet.
References GSDD::GSDD().
unsigned long int GSDD::size () const inherited
Returns the size in number of nodes of a SDD structure.
unsigned int GSDD::statistics () static inherited
Returns unicity table current size. Gives the number of different nodes created and not yet destroyed.
References UniqueTable< T >::size().
Referenced by MemoryManager::nbSDD().
int GSDD::variable () const inherited
Returns a node's variable.
References GSDD::concret, and _GSDD::variable.
Referenced by dotExporter::collect(), hDotExporter::collect(), _SDED_Add::create(), _SDED_Mult::create(), _SDED_Minus::create(), StrongMLShom::eval(), sns::SApply2k::eval(), sns::Mult::eval(), _SDED_Mult::eval(), sns::SDomExtract::eval(), _SDED_Minus::eval(), sns::LocalApply::eval(), StrongShom::eval(), _SDED_Concat::eval(), sns::SLocalApply::eval(), sns::And::eval(), sns::Add::eval(), sns::RecFireSat::eval(), sns::Fixpoint::eval(), _GShom::eval_skip(), sns::LocalApply::has_image(), StrongShom::has_image(), sns::SLocalApply::has_image(), sns::And::has_image(), _GShom::has_image_skip(), GSDD::print(), and sns::SApply2k::skip_variable().
Member Data Documentation
const GSDD GSDD::null static inherited
The non-accepting terminal.
As DDD are a zero-suppressed variant of decision diagrams, paths leading to null are suppressed. Only the empty set is represented by null.
Referenced by SDED::add(), apply2k(), _GShom::compose(), _SDED_Add::create(), _SDED_Mult::create(), _SDED_Minus::create(), _SDED_Concat::create(), _SDED_Shom::create(), GSDD::empty(), SDED::eval(), StrongMLShom::eval(), sns::Constant::eval(), _SDED_Add::eval(), sns::SApply2k::eval(), sns::Mult::eval(), _SDED_Mult::eval(), sns::SDomExtract::eval(), _SDED_Minus::eval(), sns::LocalApply::eval(), StrongShom::eval(), _SDED_Concat::eval(), sns::SLocalApply::eval(), sns::SNotCond::eval(), sns::And::eval(), sns::Add::eval(), sns::RecFireSat::eval(), sns::Fixpoint::eval(), _GShom::eval_skip(), fixpoint(), GSDD::GSDD(), GShom::has_image(), sns::Inter::has_image(), sns::LocalApply::has_image(), StrongShom::has_image(), sns::SLocalApply::has_image(), sns::SNotCond::has_image(), sns::And::has_image(), sns::Add::has_image(), sns::Compose::has_image(), _GShom::has_image_skip(), sns::Compose::invert(), sns::Constant::is_selector(), sns::SApply2k::is_selector(), MySDDNbStates::nbStates(), GShom::operator()(), GSDD::print(), and dotExporter::printLevels().
const GSDD GSDD::one static inherited
The accepting terminal. This is the basic leaf for accepted sequences.
Referenced by apply2k(), dotExporter::collect(), hDotExporter::collect(), _SDED_Add::create(), _SDED_Mult::create(), _SDED_Minus::create(), _SDED_Concat::create(), StrongMLShom::eval(), sns::SDomExtract::eval(), sns::LocalApply::eval(), StrongShom::eval(), sns::SLocalApply::eval(), sns::SNotCond::eval(), sns::And::eval(), sns::Add::eval(), sns::RecFireSat::eval(), sns::Fixpoint::eval(), _GShom::eval_skip(), sns::LocalApply::has_image(), StrongShom::has_image(), sns::SLocalApply::has_image(), sns::And::has_image(), _GShom::has_image_skip(), MySDDNbStates::nbStates(), GSDD::print(), and dotExporter::printLevels().
const GSDD GSDD::top static inherited
The approximation terminal.
This represents any finite set of assignment sequences. In a "normal" usage pattern, top terminals should not be produced. In fact the result may be incorrect if Top is encountered at any but the highest level.
Referenced by apply2k(), dotExporter::collect(), hDotExporter::collect(), _SDED_Add::create(), _SDED_Mult::create(), _SDED_Minus::create(), _SDED_Concat::create(), StrongMLShom::eval(), sns::SDomExtract::eval(), sns::LocalApply::eval(), StrongShom::eval(), sns::SLocalApply::eval(), sns::SNotCond::eval(), sns::And::eval(), sns::Add::eval(), sns::RecFireSat::eval(), sns::Fixpoint::eval(), _GShom::eval_skip(), sns::LocalApply::has_image(), StrongShom::has_image(), sns::SLocalApply::has_image(), sns::And::has_image(), _GShom::has_image_skip(), MySDDNbStates::nbStates(), StrongShom::phiOne(), GSDD::print(), and dotExporter::printLevels().
The documentation for this class was generated from the following files:
SDD.h
SDD.cpp
Please comment this page and report errors about it on the RefDocComments page.