DDD: DDD.cpp File Reference
DDD.cpp File Reference
#include <cstdlib>
#include <cstring>
#include <string>
#include <iostream>
#include <vector>
#include <set>
#include <cassert>
#include <map>
#include <sstream>
#include <limits>
#include "ddd/util/configuration.hh"
#include "ddd/DDD.h"
#include "ddd/UniqueTableId.hh"
#include "ddd/DED.h"
#include "MemoryManager.h"
Classes
class _GDDD
struct _GDDD::custom_new_t
an empty struct tag type used to disambiguate between different variants of the operator new for _GDDD.
class MySize
class MyNbStates
Typedefs
typedef UniqueTableId< _GDDD,
GDDD::id_t > DDDutable
Functions
std::ostream & operator<< (std::ostream &os, const GDDD &g)
Textual output of DDD into a stream in (relatively) human readable format.
void saveDDD (std::ostream &os, std::vector< DDD > list)
void loadDDD (std::istream &is, std::vector< DDD > &list)
Variables
std::map< int, std::string > mapVarName
Typedef Documentation
typedef UniqueTableId<_GDDD,GDDD::id_t> DDDutable
Function Documentation
void loadDDD (std::istream & is, std::vector< DDD > & list)
References GDDD::null, GDDD::one, and GDDD::top.
std::ostream& operator<< (std::ostream & os, const GDDD & g)
Textual output of DDD into a stream in (relatively) human readable format.
Don't use it with large number of paths as each element is printed on a different line
References GDDD::print().
void saveDDD (std::ostream & os, std::vector< DDD > list)
References GDDD::begin(), GDDD::end(), GDDD::null, GDDD::one, GDDD::top, and GDDD::variable().
Variable Documentation
std::map<int,std::string> mapVarName
Referenced by GDDD::getvarName(), and GDDD::varName().
Please comment this page and report errors about it on the RefDocComments page.